[theme]
primaryColor = "#e65100"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f9fc"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
